// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function About$page(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("h1", {
                    children: "This is about page"
                  }),
              className: "flex min-h-screen flex-col items-center justify-between p-24"
            });
}

var page = About$page;

export {
  page ,
}
/* react/jsx-runtime Not a pure module */
