'use client'
// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import $$Image from "next/image";
import * as $$Navigation from "next/navigation";
import * as JsxRuntime from "react/jsx-runtime";

function Navbar$default(props) {
  var pathname = $$Navigation.usePathname();
  return JsxRuntime.jsx("nav", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx(Link, {
                            href: "/",
                            scroll: true,
                            prefetch: true,
                            children: JsxRuntime.jsx($$Image, {
                                  src: "/next.svg",
                                  width: 300,
                                  height: 61,
                                  alt: "next.js logo",
                                  priority: true,
                                  className: "w-20"
                                })
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx(Link, {
                                    href: "/",
                                    className: "font-bold text-lg " + (
                                      pathname === "/" ? "underline text-teal-700" : ""
                                    ) + " transition-all",
                                    children: "Home"
                                  }),
                              JsxRuntime.jsx(Link, {
                                    href: "/about",
                                    className: "font-bold text-lg " + (
                                      pathname === "/about" ? "underline text-teal-700" : ""
                                    ) + " transition-all",
                                    children: "About"
                                  })
                            ],
                            className: "flex gap-4"
                          })
                    ],
                    className: "flex items-center justify-between"
                  }),
              className: "container p-4"
            });
}

var Link$1;

var $$Image$1;

var $$Navigation$1;

var $$default = Navbar$default;

export {
  Link$1 as Link,
  $$Image$1 as $$Image,
  $$Navigation$1 as $$Navigation,
  $$default as default,
}
/* next/link Not a pure module */
