// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Counter from "./components/Counter.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Home$page(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(Counter.make, {}),
              className: "min-h-[calc(100vh-60px)] flex flex-col items-center p-24"
            });
}

var page = Home$page;

export {
  page ,
}
/* Counter Not a pure module */
