import './globals.css'
import Navbar from './components/Navbar.mjs'

/**  @type { import('next').Metadata } */
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
